# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a base Python image
FROM python:3.10-slim as base

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml and install build system
COPY pyproject.toml /app/

# Install dependencies using pip
RUN pip install hatchling && hatchling build

# Copy the rest of the application code
COPY src /app/src

# Set the entry point to run the server
ENTRYPOINT ["python", "-m", "mcp_dbutils", "--config", "/app/config.yaml"]
